### ISSUE TITLE
Broken image in npm package README

### ISSUE THREAD

**Issue by nicfv** [bengadbois/nopejs#11]
Here is the contents of README.md in [npm](https://www.npmjs.com/package/@bengadbois/nopejs?activeTab=code):

```md
![Nope](http://i.imgur.com/dW3Nt4A.png)

NopeJS says "Nope!" to Javascript and stops all execution
```

I suggest changing the image URL to the following:

```md
![Nope](https://raw.githubusercontent.com/bengadbois/nopejs/master/logo.png)
```

Thank you. I hope this contribution helps to grow the nopejs community.

**Comment by bengadbois** [comment]
Not sure where you got the imgur link, https://raw.githubusercontent.com/bengadbois/nopejs/master/README.md doesn't have that, and has been unchanged for years

**Comment by nicfv** [comment]
Here's your answers. It's in the npm repository.

![image](https://github.com/bengadbois/nopejs/assets/24358775/3e1055d6-701b-4500-bbdf-47b804b67321)

![image](https://github.com/bengadbois/nopejs/assets/24358775/ebce06ae-4703-410d-abae-8a7126b13b84)
