### ISSUE TITLE
Actually say "nope", instead of nothing.

### ISSUE THREAD

**Issue by cjwelborn** [bengadbois/nopejs#3]
# Problem:

The documentation for `NopeJS` clearly states:

>NopeJS says "nope!" to the JS and stops execution.

But it really isn't saying anything (`throw '';`).  Newcomers to `NopeJS` might be confused to find out that execution was in fact stopped, but nothing was actually said to the JS.

## Resolution 1:
The `throw` statement should be switched to `throw 'nope!'`.

## Resolution 2:
Change the documentation to reflect reality:
```bash
sed -i 's/"nope!"/""/' README.md
```
Resulting in:
>NopeJS says "" to the JS and stops execution.

## Comments:
I prefer resolution number one. I know this would result in a whopping `5 byte` addition to all source files (even the minified versions), which in turn will make the code almost twice as slow (not tested), but I think it would be worth it in the long run.

**Comment by bengadbois** [comment]
After running some rigorous benchmarks and tests, I determined that the overhead of "nope!" vs empty string was insignificant compared to the overhead of letting JS continue to run.

This has now been addressed in v1.1.0
